### ISSUE TITLE
Make the game pause, when user or computer wins

### ISSUE THREAD

**Issue by mamontov-cpp** [stephfubi/pong#1]
The game should pause and wait for user input (from keyboard for example), when the ball goes out of game field.

**Comment by mamontov-cpp** [comment]
Судя по всему, для этого надо подпатчить класс ball - завести у него флаг bool isPaused, который устанавливать в true в Update перед вызовом Start.

Саму ball::Start надо изменить так, что если isPaused установлен, то rb.velocity устанавливается в 0, иначе в ту скорость, которая у вас была.

В самом ball::Update можно добавить проверку, что если флаг isPaused установлен, и http://docs.unity3d.com/ScriptReference/Input-anyKey.html - выполняется, то вызвать Start повторно
.

По идее это должно работать.

**Comment by stephfubi** [comment]
i have made all the corrections...  please check the link i sent on vk
https://github.com/stephfubi/summerPracticals_final

**Comment by mamontov-cpp** [comment]
Проверил - да, работает. Скиньте мне отчет для сдачи, я его проверю - и если все хорошо, приходите в четверг (в группе написано время).

**Comment by stephfubi** [comment]
скинула....  через vk
